# Defining this here allows us to atomically change both the code and the go version used to build the code in CI.
build_root_image:
  namespace: openshift
  name: release
  tag: rhel-9-release-golang-1.19-openshift-4.14
