apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: windows-exporter
  name: windows-exporter
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
      relabelings:
        - action: replace
          regex: (.*)
          replacement:
          sourceLabels:
            - __meta_kubernetes_endpoint_address_target_name
          targetLabel: instance
        - action: labelmap
          source_labels: [container_id]
          replacement: pod
  selector:
    matchLabels:
      name: windows-exporter