name: Weekly Submodule Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Initialize submodules
        run: |
          git submodule update --init
          git submodule foreach 'git fetch origin'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current branch
        id: branch
        run: echo "name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Update submodules
        id: update
        run: |
          ./hack/update_submodules.sh ${{ steps.branch.outputs.name }}
          new_branch=$(git branch --list "${{ steps.branch.outputs.name }}-submodule-update-*" | head -1 | xargs)
          echo "new_branch=$new_branch" >> $GITHUB_OUTPUT

      - name: Push and create Pull Request
        run: |
          git push origin ${{ steps.update.outputs.new_branch }} --force
          gh pr create --title "Weekly submodule updates for ${{ steps.branch.outputs.name }}" \
            --body "Automated weekly update of git submodules and dependencies." \
            --base ${{ steps.branch.outputs.name }} \
            --head ${{ steps.update.outputs.new_branch }} \
            --label dependencies || echo "PR may already exist"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
